### PR TITLE
Add @gifnksm as contributor to package.json.

### PR DESCRIPTION
**Pull request by saneyuki**
We need to add @gifnksm as contributor by https://github.com/saneyuki/option-t.js/pull/62.

[Review on Reviewable](https://reviewable.io/reviews/saneyuki/option-t.js/63)

### CODE REVIEW

**Comment by saneyuki** [comment]
@gifnksm could you review this pull request?

**Comment by gifnksm** [comment]
r+

**Comment by gifnksm** [comment]
Thanks!

**Comment by saneyuki** [comment]
@gifnksm 

you're welcome!

I've just released [v0.9.2](https://github.com/saneyuki/option-t.js/blob/master/CHANGELOG.md#092) which includes [your pull request](https://github.com/saneyuki/option-t.js/pull/62).

Enjoy hacking :)

**Pull request merged**
