### PR TITLE
Add the document about idioms

### PR DESCRIPTION
**Pull request by saneyuki**
- Instead of prividing a new features, we provide some idioms as the document.

---
This change is [Reviewable](https://reviewable.io/reviews/saneyuki/option-t.js/159)

### CODE REVIEW

**Comment by nekoya** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/IDIOM.md, line 19 at r1](https://reviewable.io:443/reviews/saneyuki/option-t.js/159#-KYxC5B3eHH3DAiZT7vF:-KYxC5B4d_ktjYXTQC3r:b6m6iyb) ([raw file](https://github.com/saneyuki/option-t.js/blob/e0a2c667889c18951b0180496acef7625b3639f2/docs/IDIOM.md#L19)):*
> ```Markdown
> ```typescript
> function unwrapOrUndefined<T>(option: Option<T>): T | undefined {
>   let result: T | undefined = option.isSome ? option.unwrap() : undefined;
> ```

Would you like to use 'let' here? is not 'const'?

---

*[docs/IDIOM.md, line 24 at r1](https://reviewable.io:443/reviews/saneyuki/option-t.js/159#-KYxD8QtLbeL03PWyS9f:-KYxD8QuE8pVv8y_zmUI:bps1s89) ([raw file](https://github.com/saneyuki/option-t.js/blob/e0a2c667889c18951b0180496acef7625b3639f2/docs/IDIOM.md#L24)):*
> ```Markdown
> 
> function unwrapOrNull<T>(option: Option<T>): T | null {
>   let result: T | null = option.isSome ? option.unwrap() : null;
> ```

here too

---

*[docs/IDIOM.md, line 59 at r1](https://reviewable.io:443/reviews/saneyuki/option-t.js/159#-KYxDYPpG1QRLJ3_SPOh:-KYxDYPpG1QRLJ3_SPOi:b-xuzjqy) ([raw file](https://github.com/saneyuki/option-t.js/blob/e0a2c667889c18951b0180496acef7625b3639f2/docs/IDIOM.md#L59)):*
> ```Markdown
>   }, (v: T) => {
>     result.ok = true;
>     result.value = v;
> ```

It's seem to entirely new result. Do you like update existent `result`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/saneyuki/option-t.js/159)*

**Comment by nekoya** [comment]
That's great work!

In addition, I hope to add links to original Rust documentation for example,

- https://doc.rust-lang.org/std/result/
- https://doc.rust-lang.org/book/generics.html

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/saneyuki/option-t.js/159#-:-KYxF-uDDL9z1pcOqZLE:bwsoqj0)*

**Comment by saneyuki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/IDIOM.md, line 59 at r1](https://reviewable.io:443/reviews/saneyuki/option-t.js/159#-KYxDYPpG1QRLJ3_SPOh:-KZ09OUvmfY8foPu098H:bsyhtgy) ([raw file](https://github.com/saneyuki/option-t.js/blob/e0a2c667889c18951b0180496acef7625b3639f2/docs/IDIOM.md#L59)):*
<details><summary><i>Previously, nekoya (Ryo Miyake) wrote…</i></summary><blockquote>

It's seem to entirely new result. Do you like update existent `result`?
</blockquote></details>

This `result` will be created newly on calling this functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/saneyuki/option-t.js/159)*

**Comment by nekoya** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/saneyuki/option-t.js/159)*

**Comment by nekoya** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/saneyuki/option-t.js/159)*

**Comment by saneyuki** [comment]
@homu r+

**Pull request merged**
